import csv
import json
from collections import defaultdict
from statistics import mean, stdev

from ..lib.ablation_harness import RECIPES
from ..paths import RESULTS_DIR, REPORTS_DIR

IN_DIR = RESULTS_DIR / "ablation"
OUT_MD = REPORTS_DIR / "RESULTS_ablation.md"
OUT_CSV = RESULTS_DIR / "ablation_summary.csv"

MODELS = ["BPR", "NeuMF", "LightGCN"]
DATASETS = ["musical", "baby", "cellphone", "healthcare"]
SEEDS = (42, 123, 2026)
METRICS = [("HR@20", "HitRatio@20"), ("NDCG@20", "NDCG@20"), ("Recall@20", "Recall@20")]
DATASET_LABEL = {"musical": "Musical Instruments", "baby": "Baby Products",
                 "cellphone": "Cell Phones \\& Acc.",
                 "healthcare": "Health \\& Household"}


def load_all():
    data = defaultdict(dict)
    rho = defaultdict(dict)
    for path in sorted(IN_DIR.glob("*.json")):
        with open(path, encoding="utf-8-sig") as f:
            payload = json.load(f)
        model = payload["model"]
        dataset = payload["dataset"]
        seed = int(payload["seed"])
        for recipe, metrics in payload["recipes"].items():
            for disp, key in METRICS:
                if key in metrics:
                    data[(model, dataset, recipe, disp)][seed] = float(metrics[key])
            if "counterfactual_rate" in metrics:
                rho[(model, dataset, recipe)][seed] = float(metrics["counterfactual_rate"])
    return data, rho


def missing(by_seed):
    return [f"seed{s}" for s in SEEDS if s not in by_seed]


def missing_label(by_seed):
    return f"missing [{', '.join(missing(by_seed))}]"


def models_present(data):
    seen = {key[0] for key in data}
    return ([m for m in MODELS if m in seen]
            + sorted(seen - set(MODELS)))


def fmt_cell(by_seed):
    if missing(by_seed):
        return missing_label(by_seed)
    values = [by_seed[s] for s in SEEDS]
    return f"{mean(values):.4f} ± {stdev(values):.4f}"


def fmt_pct(by_seed):
    if not by_seed:
        return "–"
    if missing(by_seed):
        return missing_label(by_seed)
    values = [by_seed[s] for s in SEEDS]
    return f"{mean(values) * 100:.2f} ± {stdev(values) * 100:.2f}%"


def render_markdown(data, rho):
    lines = ["# Causal-sampling ablation: mean +/- std across seeds\n",
             f"_Source: {IN_DIR}/. Re-generated by `aggregate_ablation.py`._\n",
             "\n`uniform` draws negatives from the whole catalog; `causal` draws only "
             "from items that existed at the positive's timestamp. Nothing else "
             "differs between the two cells.\n"]

    for model in models_present(data):
        lines.append(f"\n## {model}\n")
        best = {}
        for ds in DATASETS:
            for disp, _ in METRICS:
                means = [(r, mean(v.values())) for r in RECIPES
                         for v in [data[(model, ds, r, disp)]] if v and not missing(v)]
                if means:
                    best[(ds, disp)] = max(means, key=lambda x: x[1])[0]

        lines.append("| Dataset | Recipe | HR@20 | NDCG@20 | Recall@20 | ρ | seeds |")
        lines.append("|---|---|---|---|---|---|---|")
        for ds in DATASETS:
            for recipe in RECIPES:
                row_vals = []
                n_seeds = 0
                for disp, _ in METRICS:
                    vals = data[(model, ds, recipe, disp)]
                    n_seeds = max(n_seeds, len(vals))
                    cell = fmt_cell(vals)
                    if best.get((ds, disp)) == recipe and not missing(vals):
                        cell = f"**{cell}**"
                    row_vals.append(cell)
                lines.append(f"| {DATASET_LABEL[ds]} | {recipe} | "
                             f"{row_vals[0]} | {row_vals[1]} | {row_vals[2]} | "
                             f"{fmt_pct(rho[(model, ds, recipe)])} | {n_seeds} |")

    lines.append("\nρ is the counterfactual-negative rate: the fraction of training "
                 "negatives whose first-seen timestamp post-dates their paired "
                 "positive. It is 0 by construction under `causal`. A cell lacking "
                 "any of seeds 42, 123, 2026 shows only which seeds are missing.\n")
    return "\n".join(lines) + "\n"


def write_csv(data, rho):
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_CSV, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["model", "dataset", "recipe", "metric", "mean", "std", "n",
                    "missing_seeds"])
        rows = sorted(data.items())
        rows += [((m, d, r, "rho"), v) for (m, d, r), v in sorted(rho.items())]
        for (model, ds, recipe, disp), by_seed in rows:
            if not by_seed:
                continue
            vals = list(by_seed.values())
            m = mean(vals)
            s = stdev(vals) if len(vals) > 1 else 0.0
            w.writerow([model, ds, recipe, disp, f"{m:.6f}", f"{s:.6f}", len(vals),
                        " ".join(missing(by_seed))])
    print(f"[aggregate_ablation] wrote {OUT_CSV}")


def main():
    if not IN_DIR.exists():
        raise SystemExit(f"no input dir: {IN_DIR}")
    data, rho = load_all()
    if not data:
        raise SystemExit(f"no JSONs in {IN_DIR}")
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text(render_markdown(data, rho), encoding="utf-8")
    print(f"[aggregate_ablation] wrote {OUT_MD}")
    write_csv(data, rho)


if __name__ == "__main__":
    main()
