"""Aggregate per-seed 2x2 ablation JSONs into mean+/-std markdown tables.

Inputs:  research/results/2x2/<model>_<dataset>_seed<n>.json (written by
         research.runners.ablation_bpr / ablation_neumf / ablation_lightgcn).
Outputs: research/reports/RESULTS_2x2.md  (markdown tables)
         research/results/2x2_summary.csv (tidy CSV for figures)
"""

import csv
import json
from collections import defaultdict
from pathlib import Path
from statistics import mean, stdev

from ..paths import RESULTS_DIR, REPORTS_DIR

IN_DIR = RESULTS_DIR / "2x2"
OUT_MD = REPORTS_DIR / "RESULTS_2x2.md"
OUT_CSV = RESULTS_DIR / "2x2_summary.csv"

MODELS = ["BPR", "NeuMF", "LightGCN"]
DATASETS = ["baby", "cellphone", "healthcare", "movielens1m"]
RECIPES = ["shuffle+uniform", "shuffle+causal", "win10+uniform", "win10+causal"]
METRICS = [("HR@20", "HitRatio@20"), ("NDCG@20", "NDCG@20"), ("Recall@20", "Recall@20")]
DATASET_LABEL = {"baby": "Baby Products", "cellphone": "Cell Phones \\& Acc.",
                 "healthcare": "Health \\& Household",
                 "movielens1m": "MovieLens-1M"}


def load_all():
    # data[(model, dataset, recipe, display_metric)] -> list[float]
    data = defaultdict(list)
    for path in sorted(IN_DIR.glob("*.json")):
        with open(path, encoding="utf-8") as f:
            payload = json.load(f)
        model = payload["model"]
        dataset = payload["dataset"]
        for recipe, metrics in payload["recipes"].items():
            for disp, key in METRICS:
                if key in metrics:
                    data[(model, dataset, recipe, disp)].append(float(metrics[key]))
    return data


def fmt_cell(values):
    if not values:
        return "TBD"
    if len(values) == 1:
        return f"{values[0]:.4f}"
    return f"{mean(values):.4f} ± {stdev(values):.4f}"


def render_markdown(data):
    lines = ["# 2x2 ablation: mean +/- std across seeds\n",
             f"_Source: {IN_DIR}/. Re-generated by `aggregate_2x2.py`._\n"]

    for model in MODELS:
        lines.append(f"\n## {model}\n")
        # Find best mean per (dataset, metric) for bolding.
        best = {}
        for ds in DATASETS:
            for disp, _ in METRICS:
                cands = [(recipe, data[(model, ds, recipe, disp)])
                         for recipe in RECIPES]
                means = [(r, mean(v)) for r, v in cands if v]
                if means:
                    best[(ds, disp)] = max(means, key=lambda x: x[1])[0]

        lines.append("| Dataset | Recipe | HR@20 | NDCG@20 | Recall@20 | seeds |")
        lines.append("|---|---|---|---|---|---|")
        for ds in DATASETS:
            for recipe in RECIPES:
                row_vals = []
                n_seeds = 0
                for disp, _ in METRICS:
                    vals = data[(model, ds, recipe, disp)]
                    n_seeds = max(n_seeds, len(vals))
                    cell = fmt_cell(vals)
                    if best.get((ds, disp)) == recipe and vals:
                        cell = f"**{cell}**"
                    row_vals.append(cell)
                lines.append(f"| {DATASET_LABEL[ds]} | {recipe} | "
                             f"{row_vals[0]} | {row_vals[1]} | {row_vals[2]} | {n_seeds} |")
    return "\n".join(lines) + "\n"


def write_csv(data):
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_CSV, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["model", "dataset", "recipe", "metric", "mean", "std", "n"])
        for (model, ds, recipe, disp), vals in sorted(data.items()):
            if not vals:
                continue
            m = mean(vals)
            s = stdev(vals) if len(vals) > 1 else 0.0
            w.writerow([model, ds, recipe, disp, f"{m:.6f}", f"{s:.6f}", len(vals)])
    print(f"[aggregate_2x2] wrote {OUT_CSV}")


def main():
    if not IN_DIR.exists():
        raise SystemExit(f"no input dir: {IN_DIR}")
    data = load_all()
    if not data:
        raise SystemExit(f"no JSONs in {IN_DIR}")
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text(render_markdown(data), encoding="utf-8")
    print(f"[aggregate_2x2] wrote {OUT_MD}")
    write_csv(data)


if __name__ == "__main__":
    main()
