"""Aggregate per-seed ablation JSONs into mean+/-std markdown tables.

Inputs:  research/results/ablation/<model>_<dataset>_seed<n>.json (written by
         research.runners.ablation_bpr / ablation_neumf / ablation_lightgcn).
Outputs: research/reports/RESULTS_ablation.md  (markdown tables)
         research/results/ablation_summary.csv (tidy CSV for figures)
"""

import csv
import json
from collections import defaultdict
from statistics import mean, stdev

from ..lib.ablation_harness import RECIPES
from ..paths import RESULTS_DIR, REPORTS_DIR

IN_DIR = RESULTS_DIR / "ablation"
OUT_MD = REPORTS_DIR / "RESULTS_ablation.md"
OUT_CSV = RESULTS_DIR / "ablation_summary.csv"

MODELS = ["BPR", "NeuMF", "LightGCN"]
DATASETS = ["musical", "baby", "cellphone", "healthcare"]
METRICS = [("HR@20", "HitRatio@20"), ("NDCG@20", "NDCG@20"), ("Recall@20", "Recall@20")]
DATASET_LABEL = {"musical": "Musical Instruments", "baby": "Baby Products",
                 "cellphone": "Cell Phones \\& Acc.",
                 "healthcare": "Health \\& Household"}


def load_all():
    # data[(model, dataset, recipe, display_metric)] -> list[float]
    data = defaultdict(list)
    # rho[(model, dataset, recipe)] -> list[float]
    rho = defaultdict(list)
    for path in sorted(IN_DIR.glob("*.json")):
        # utf-8-sig tolerates a BOM if a file was ever hand-edited on Windows.
        with open(path, encoding="utf-8-sig") as f:
            payload = json.load(f)
        model = payload["model"]
        dataset = payload["dataset"]
        for recipe, metrics in payload["recipes"].items():
            for disp, key in METRICS:
                if key in metrics:
                    data[(model, dataset, recipe, disp)].append(float(metrics[key]))
            if "counterfactual_rate" in metrics:
                rho[(model, dataset, recipe)].append(
                    float(metrics["counterfactual_rate"]))
    return data, rho


def fmt_cell(values):
    if not values:
        return "TBD"
    if len(values) == 1:
        return f"{values[0]:.4f}"
    return f"{mean(values):.4f} ± {stdev(values):.4f}"


def fmt_pct(values):
    if not values:
        return "–"
    return f"{mean(values) * 100:.2f}%"


def render_markdown(data, rho):
    lines = ["# Causal-sampling ablation: mean +/- std across seeds\n",
             f"_Source: {IN_DIR}/. Re-generated by `aggregate_ablation.py`._\n",
             "\n`uniform` draws negatives from the whole catalog; `causal` draws only "
             "from items that existed at the positive's timestamp. Nothing else "
             "differs between the two cells.\n"]

    for model in MODELS:
        lines.append(f"\n## {model}\n")
        # Find best mean per (dataset, metric) for bolding.
        best = {}
        for ds in DATASETS:
            for disp, _ in METRICS:
                means = [(r, mean(v)) for r in RECIPES
                         for v in [data[(model, ds, r, disp)]] if v]
                if means:
                    best[(ds, disp)] = max(means, key=lambda x: x[1])[0]

        lines.append("| Dataset | Recipe | HR@20 | NDCG@20 | Recall@20 | ρ | seeds |")
        lines.append("|---|---|---|---|---|---|---|")
        for ds in DATASETS:
            for recipe in RECIPES:
                row_vals = []
                n_seeds = 0
                for disp, _ in METRICS:
                    vals = data[(model, ds, recipe, disp)]
                    n_seeds = max(n_seeds, len(vals))
                    cell = fmt_cell(vals)
                    if best.get((ds, disp)) == recipe and vals:
                        cell = f"**{cell}**"
                    row_vals.append(cell)
                lines.append(f"| {DATASET_LABEL[ds]} | {recipe} | "
                             f"{row_vals[0]} | {row_vals[1]} | {row_vals[2]} | "
                             f"{fmt_pct(rho[(model, ds, recipe)])} | {n_seeds} |")

    lines.append("\nρ is the counterfactual-negative rate: the fraction of training "
                 "negatives whose first-seen timestamp post-dates their paired "
                 "positive. It is 0 by construction under `causal`.\n")
    return "\n".join(lines) + "\n"


def write_csv(data, rho):
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_CSV, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["model", "dataset", "recipe", "metric", "mean", "std", "n"])
        for (model, ds, recipe, disp), vals in sorted(data.items()):
            if not vals:
                continue
            m = mean(vals)
            s = stdev(vals) if len(vals) > 1 else 0.0
            w.writerow([model, ds, recipe, disp, f"{m:.6f}", f"{s:.6f}", len(vals)])
        for (model, ds, recipe), vals in sorted(rho.items()):
            if not vals:
                continue
            m = mean(vals)
            s = stdev(vals) if len(vals) > 1 else 0.0
            w.writerow([model, ds, recipe, "rho", f"{m:.6f}", f"{s:.6f}", len(vals)])
    print(f"[aggregate_ablation] wrote {OUT_CSV}")


def main():
    if not IN_DIR.exists():
        raise SystemExit(f"no input dir: {IN_DIR}")
    data, rho = load_all()
    if not data:
        raise SystemExit(f"no JSONs in {IN_DIR}")
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text(render_markdown(data, rho), encoding="utf-8")
    print(f"[aggregate_ablation] wrote {OUT_MD}")
    write_csv(data, rho)


if __name__ == "__main__":
    main()
